# Generated by Django 5.1.2 on 2025-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url2",
            field=models.URLField(blank=True),
        ),
    ]
