# Generated by Django 5.1.2 on 2025-04-28 19:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0002_project_url2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
